# Generated by Django 4.1.1 on 2022-09-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
